### ISSUE TITLE
emscripten build error

### ISSUE THREAD

**Issue by unicomp21** [floooh/sokol-samples#105]
root@e1c5d8668d31:/tmp/sokol-samples# ./fips setup emscripten
=== updating emscripten SDK at '/tmp/fips-sdks/emsdk'
Already up to date.
=== installing emscripten tools for 'latest'
Resolving SDK alias 'latest' to '3.1.20'
Resolving SDK version '3.1.20' to 'sdk-releases-upstream-d92c8639f406582d70a5dde27855f74ecf602f45-64bit'
Installing SDK 'sdk-releases-upstream-d92c8639f406582d70a5dde27855f74ecf602f45-64bit'..
Installing tool 'node-14.18.2-64bit'..
Downloading: /tmp/fips-sdks/emsdk/zips/node-v14.18.2-linux-x64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.18.2-linux-x64.tar.xz, 21848416 Bytes
Unpacking '/tmp/fips-sdks/emsdk/zips/node-v14.18.2-linux-x64.tar.xz' to '/tmp/fips-sdks/emsdk/node/14.18.2_64bit'
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
['tar', '-xf', '/tmp/fips-sdks/emsdk/zips/node-v14.18.2-linux-x64.tar.xz', '--strip', '1'] failed with error code 2!
error: installation failed!
=== activating emscripten SDK version 'latest'
embedded mode is now the only mode available
Resolving SDK alias 'latest' to '3.1.20'
Resolving SDK version '3.1.20' to 'sdk-releases-upstream-d92c8639f406582d70a5dde27855f74ecf602f45-64bit'
error: error: tool is not installed and therefore cannot be activated: 'node-14.18.2-64bit'

**Comment by floooh** [comment]
Hmm... this looks like the regular emsdk setup is breaking because it expects the 'xz' tool to be installed (the fips setup wrapper code doesn't call 'tar -xf' itself).

Does the same error happen when you follow the "official" Emscripten SDK installation here?

https://emscripten.org/docs/getting_started/downloads.html

...if yes we should file a bug in the emsdk repository, if not then it must actually some bug in fips that I need to fix.
