### ISSUE TITLE
Bunnymark / suzannemark

### ISSUE THREAD

**Issue by munrocket** [floooh/sokol-samples#147]
Can we make example like here: https://www.goodboydigital.com/pixijs/bunnymark/

Or here:
https://threejs.org/examples/?q=performance#webgpu_performance_renderbundle

Will be interesting to compare WebGL/WebGPU backends and Emscripten overall.

**Comment by floooh** [comment]
This is pretty close:

- WebGL2: https://floooh.github.io/sokol-html5/drawcallperf-sapp.html
- WebGPU: https://floooh.github.io/sokol-webgpu/drawcallperf-sapp.html 

It basically measures 3D API overhead of a simple uniform update + draw call. This also shows that WebGL2 can be faster than WebGPU currently (mainly because WebGPU's `setBindGroup()` has a surprisingly high overhead.

Some details are mentioned in this blog post: https://floooh.github.io/2023/10/16/sokol-webgpu.html

The biggest differences are on Windows, where the native D3D11 versions manages 450k draw calls before dropping below 60 Hz, WebGL2 around 64k and WebGPU 16k.

**Comment by floooh** [comment]
PS: if you want to check instancing performance:

https://floooh.github.io/sokol-html5/instancing-sapp.html

...but this won't tell you anything about 3D API overhead, because it's a single draw call.

**Comment by munrocket** [comment]
ty
