### ISSUE TITLE
ADVANCED TOPIC: Injecting native 3D-API textures

### ISSUE THREAD

**Issue by Oldes** [floooh/sokol-samples#38]
I know that you are in the middle of work on `cgltf`, but if you had some spare time, could you bring some light (sample) into the usage of native textures? Now there is only [this](https://github.com/floooh/sokol/blob/51f4c084c6ba117e12d612c6ab625c0fb1877aeb/sokol_gfx.h#L1325-L1335) and [that](https://github.com/floooh/sokol/blob/51f4c084c6ba117e12d612c6ab625c0fb1877aeb/sokol_gfx.h#L1220-L1241) mention so far.

Or is there some other documentation somewhere?

**Comment by floooh** [comment]
The backend-specific sokol-samples each have one example for injecting buffers and textures:

- GL: https://github.com/floooh/sokol-samples/blob/master/glfw/inject-glfw.c
- Metal: https://github.com/floooh/sokol-samples/blob/master/metal/inject-metal.mm
- D3D11: https://github.com/floooh/sokol-samples/blob/master/d3d11/inject-d3d11.c

There isn't a similar sample under the sapp-directory because it would be quite the #ifdef/#endif mess :)

**Comment by Oldes** [comment]
Thanks, I will check it. For sapp, do you plan to use Basis for native textures?

**Comment by floooh** [comment]
I will probably create a utility header which would provide some glue code between Basis Universal and sokol_gfx.h, similar to this adhoc helper code:

https://github.com/floooh/sokol-samples/blob/master/libs/basisu/basisu_sokol.cpp
