### ISSUE TITLE
high-dpi macos display with `desc.high_dpi = true` and `desc.fullscreen = false` doesnt fill the window

### ISSUE THREAD

**Issue by prime31** [floooh/sokol-samples#51]
Using the imgui-highdpi-sapp as an example, just setting fullscreen = false results in the following:

<img width="1136" alt="Screen Shot 2020-01-23 at 7 55 46 PM" src="https://user-images.githubusercontent.com/60377/73043534-6bfc7380-3e1a-11ea-9e91-cdbf8fc2c5b8.png">

cube-sapp with high_dpi = true:

<img width="912" alt="Screen Shot 2020-01-23 at 7 58 48 PM" src="https://user-images.githubusercontent.com/60377/73043627-d44b5500-3e1a-11ea-9d20-f242c5789c84.png">

I'm not sure if this is an error in my understanding of how the window is setup or a bug with Sokol...

**Comment by floooh** [comment]
Aha ok, it's strange that it's the fullscreen-flag makes a difference. I need to check, but in addition to what I wrote in that other bug report, it might be that NSOpenGLView does indeed report different / weird framebuffer sizes depending on whether the application is running in fullscreen or as a regular window.

It's also interesting that when you start the imgui-highdpi sample as fullscreen, but switch to windowed mode through the macOS UI, then it looks correct. I've got a suspicion what it could be (some initialization order problem when creating the window vs NSOpenGLView object, but as I wrote in that other thread, this behaviour changed during the Catalina Beta, it might be that a fix that works for Catalina breaks it on other macOS versions). I'll try to investigate a bit during the next few days.

**Comment by floooh** [comment]
ok, see the same for the cube-sapp demo (albeit with a black background color, not red), but just commenting out the ```.fullscreen = true``` in the imgui-highdpi-sapp demo looks correct here (I'm on macOS Catalina 10.15.3 Beta (19D62e)):

<img width="1049" alt="Screen Shot 2020-01-24 at 3 47 12 PM" src="https://user-images.githubusercontent.com/1699414/73077917-6c037e80-3ec1-11ea-9717-01b29448f319.png">

There's some problem for the reported display size via sapp_width()/sapp_height(). When running the (non-highdpi) imgui-sapp demo, the reported size is 2048x1510, which is clearly a Retina resolution, but the requested resolution is 1024x768.

OTH the cube-sapp demo returns 800x600, which is the expected non-highdpi resolution, and the same as the requested resolution.

And here's the kicker: when changing the resolution of the imgui-sapp demo to 800x600, the reported resolution via sapp_width()/sapp_height() is also 800x600.

The difference I can see is that a requested framebuffer resolution of 1024x728 would result in an upscaled Retina resolution of 2048x2536, which is the display resolution of a 13" Retina Mac. But with the window title this wouldn't fit on screen and needs to be clamped.

And this clamping seems to trigger the wrongly reported size:

In the imgui-sapp demo, if I change the requested vertical resolution to 755  (instead of 768), the reported resolution matches (1024 x 755).

Just bumping the requested vertical resolution by one pixel to 1024x756, suddenly the reported resolution jumps to 2048x1510.

To be honest this looks like a bug in NSOpenGLView to me... the code in question is here:

https://github.com/floooh/sokol/blob/c54fdf95159e5ae63a21a79f46b4365ce4e2644a/sokol_app.h#L1380-L1382

I'll try to investigate a bit more...

**Comment by prime31** [comment]
Oh wow. That is super odd! It seems the NSOpenGL window just randomly decides that you want a high-dpi backbuffer for seeming random requested sizes.

**Comment by floooh** [comment]
> There's some problem for the reported display size via sapp_width()/sapp_height(). When running the (non-highdpi) imgui-sapp demo, the reported size is 2048x1510, which is clearly a Retina resolution, but the requested resolution is 1024x768.

I've added a workaround for this problem in the last code cleanup in sokol_app.h btw, along with a general cleanup of all macOS and iOS code. Closing this ticket for now until something else shows up :)
