### ISSUE TITLE
Sokol imgui load font

### ISSUE THREAD

**Issue by gavriil07** [floooh/sokol-samples#54]
Did anybody manage to load a font using s(okol)imgui?
I do:
`simgui_setup(&(simgui_desc_t){ 0 });`
`ImGuiIO *io = igGetIO();`
`F1 = ImFontAtlas_AddFontFromFileTTF(io->Fonts, "/res/fonts/RobotoMono-Regular.ttf", 25, NULL, NULL);`

at the start. After as the documentation suggest this should already work as is the only font I load...

But, one more thing you can do is use `igPushFont` && `igPopFont` after `simgui_new_frame` but still no succes.. :'(

**Comment by floooh** [comment]
I have two examples where a custom font is used, both have the font data embedded in the program though, not loading it from a file (as that wouldn't work in browsers).

See here for an example that just replaces the default font with a TTF font:

https://github.com/floooh/sokol-samples/blob/6e5d16b3df1c1dfb5f68b9d79b2f70a6b3a601bb/sapp/imgui-highdpi-sapp.cc#L35-L64

And this example uses the default font, but adds an additional icon font:

https://github.com/floooh/v6502r/blob/f2185ca6ccf0ce18ea3258e8ba163027abeefa0d/src/ui.cc#L46-L87

You need to set ```.no_default_font = true``` when calling simgui_setup(), so that the font isn't already constructed in the call to simgui_setup(), instead this must be done completely by your own code.

So the important steps are:

- call simgui_setup with ```.no_default_font``` 
- add your own fonts to ImGui's GetIO().Fonts object
- let ImGui rasterize the font, and create a sokol-gfx image from that (https://github.com/floooh/sokol-samples/blob/6e5d16b3df1c1dfb5f68b9d79b2f70a6b3a601bb/sapp/imgui-highdpi-sapp.cc#L53)
- create a sokol-gfx texture from that data and use the returned ```sg_image``` handle-id as ImGui's TexID: https://github.com/floooh/sokol-samples/blob/6e5d16b3df1c1dfb5f68b9d79b2f70a6b3a601bb/sapp/imgui-highdpi-sapp.cc#L54-L64

I haven't used PushFont/PopFont so far though, but with the procedure above to create the custom font, this should work too.

**Comment by gavriil07** [comment]
It works, thank you very much @floooh !  Did not know that I need to create an atlas for it to work:)
