### ISSUE TITLE
[Example request] Using Sokol+GLFW in Macos and Metal

### ISSUE THREAD

**Issue by MikeHart66** [floooh/sokol-samples#78]
As someone can use GLFW on Macos for Metal (see https://gist.github.com/gcatlin/987be74e2d58da96093a7598f3fbfb27 ), I am asking if a simple sokol example (maybe drawing a colored triangle) could be create and included in the samples repository.

Thank you

**Comment by floooh** [comment]
Oh, I totally forgot to close this issue, there is actually such a sample now:

https://github.com/floooh/sokol-samples/blob/master/glfw/metal-glfw.m

...it doesn't use a depth-buffer or antialiasing though (that would be quite a bit more code since CAMetalLayer only manages the actual rendering surface).
